### ISSUE TITLE
Micromanage Rates and Beds24

### ISSUE THREAD

**Issue by JuanGarciaG** [WoollyinWalesIT/jomres#113] opened 2017-02-06 15:38 UTC
Hello Vince, I noticed that you are preparing an update for the Beds24 Plugin. I want to take this opportunity to comment, that I think there is a small mistake in synchronizing the rates between Jomres and Beds24. If there is only one rate without problem, but when there is more than one and you make some change in the prices of some of them, Beds24 randomly changes any of the rates you have. There seems to be no reference linking the different rates of Jomres and Beds24 to each other.
Hope that helps.
Luck.

**Comment by jomres** [comment] 2017-02-06 15:41
Perfect timing, Juan, I was about to start work on updating the tariff --> Beds24 code this afternoon, so I'll bear what you've said in mind.

**Comment by JuanGarciaG** [comment] 2017-02-06 15:58
Perfect Vince. I realized that mistake long ago but did not want to bother too much.

Another thing I've noticed is that the locks work from Jomres to Beds24 but the same does not happen from Beds24 to Jomres. If you reduce the availability on Beds 24, that availability is not reflected in jomres.

Thank you so much

**Comment by jomres** [comment] 2017-02-06 16:08
Which locks are you referring to, Juan?

**Comment by JuanGarciaG** [comment] 2017-02-06 16:47
Locks = Black Bookings
When you do a Black Booking in Jomres, that Black Booking moves correctly to Beds24. However when you change the availability in Beds24 (it would be equivalent to creating Black Bookings in Jomres), that new availability is not transferred to Jomres, although it updates the availability in the OTAS. I think this would be a little more difficult to get, since the philosophy of Jomres is to create Black Bookings and the philosophy of Beds24 is to subtract available resources.
I'm telling you in case something happens to you.
I think it's interesting that Jomres are as homogeneous as possible to work with OTAS, but I think that you would have to create a field of availability to link with jomres.

![beds24 com control panel 2017-02-06 17-44-21](https://cloud.githubusercontent.com/assets/24232042/22656639/4125970c-ec94-11e6-861e-12b27e0573ae.png)

**Comment by jomres** [comment] 2017-02-17 14:33
I've completely re-written the section of the code that this relates to ( that was 3 days of head scratching, I can tell you ). The pricing stuff is collated using the tariff type ( an internal field ) as the main key so it *should* be exporting the prices as expected. My initial tests suggest that they are however I'll update this issue when the plugin is ready for Beta testing so that you can have a bash at it yourself.

A word of warning, for now I'm saying that the plugin will not be backwardly compatible with older version of the Beds24 plugin. I'm trying to maintain the older table structure, so in the long term it probably will be BC, but right now I'm saying it's not because I haven't had any time to test it with an older set of data.

**Comment by JuanGarciaG** [comment] 2017-02-17 16:29
Perfect, Vince, I hope you'll soon finish it.

Regards

**Comment by JuanGarciaG** [comment] 2017-03-01 17:36
Hi Vince, I'm still researching the integration of jomres with beds24 and its possible improvements.
As I said, there is a problem when the customer modifies the availability through beds24, it occurs to me that if this availability is not possible to lend it to jomres, a possible solution is that at the time of reservation jomres check that the availability in beds24 Is not equal to zero. If that's the case, "jomres" should not offer that kind of room. (I do not know if it would be possible).

On the other hand, there is a problem of duplicate emails. When a guest booking through an OTA. Beds24 sends a new reservation mail, and when that reservation is sent to jomres, "jomres" resends another new mail. I think the solution is to indicate to "jomres" that if the reservation comes from beds24 do not send any new booking emails.
In Beds24 you can deactivate the sending of mails, but that is not a good idea since in the mails of new reserve they contain the necessary data to be able to consult the data of card.

**Comment by jomres** [comment] 2017-04-03 09:30
I'll close this as it's effectively a duplicate of another issue you've posted.

**Closed by jomres** 2017-04-03 09:30 UTC
