### ISSUE TITLE
To simplify the tab "Our rooms" page object

### ISSUE THREAD

**Issue by voyagee** [WoollyinWalesIT/jomres#111] opened 2017-02-01 10:58 UTC
Like "collect a bunch of" rooms of the same type on the tab of our page number of the object. The same is true for the booking page dobooking. Objects with a large number of rooms of the same type look terrible - the endless list of the same rooms scary. 
Please, suggest possible solutions.
![100](https://cloud.githubusercontent.com/assets/25479168/22504237/637fed64-e886-11e6-8d1d-8cb42f297340.png)
![200](https://cloud.githubusercontent.com/assets/25479168/22504238/638243de-e886-11e6-9c82-ff1f26a8e1f5.png)
![300](https://cloud.githubusercontent.com/assets/25479168/22504239/638a473c-e886-11e6-81b3-8c488f70018d.png)

**Comment by jomres** [comment] 2017-05-16 06:30
Please remember that in the Classic rooms list, only property managers see the full list of rooms. Guests will see N of each ( where N = "Available rooms/tariff limit" ).

**Comment by jomres** [comment] 2017-05-16 06:34
Duplicate of #73

**Closed by jomres** 2017-05-16 06:34 UTC
Labels: Feature request
